#Run for Docker
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

bot.token=7771757315:AAG2AQLGlHb1dWXi-YfRepFe-ZDJRg8Ph54
bot.username=NewsWorldEkonomicBot

spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
memcached.servers=localhost:11211
spring.cache.type=NONE  # ????????? Spring Cache abstraction
spring.liquibase.change-log=classpath:db/changelog/master.yaml
spring.liquibase.enabled=true

